name: MRA Alternatives Tasks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: ZIP _alternatives and publish to releases/
      run: ./.github/release_mra_alternatives.sh
